"""not null attributes_id

Revision ID: 2845eb6e9edb
Revises: 464ee60b8440
Create Date: 2018-11-15 11:24:07.466186

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2845eb6e9edb'
down_revision = '464ee60b8440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="face", column_name="attributes_id", nullable=False)
    op.alter_column(table_name="unlink_attributes_log", column_name="attributes_id", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="face", column_name="attributes_id", nullable=True)
    op.alter_column(table_name="unlink_attributes_log", column_name="attributes_id", nullable=True)
    # ### end Alembic commands ###
