version: '2'

services:

  db:
    image: postgres:9.5.2
    environment:
      POSTGRES_PASSWORD: &DB_PASSWORD P@ssw0rd
      POSTGRES_USER: &DB_USERNAME video-bi
      POSTGRES_DB: &DB_NAME video-bi
    ports:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
    image: video-bi/app:latest
    environment: &ENVIRONMENT
      RAILS_ENV: production
      DB_NAME: *DB_NAME
      DB_HOST: db
      DB_USER: *DB_USERNAME
      DB_PASSWORD: *DB_PASSWORD
      SECRET_KEY_BASE: 42fac0128cae683d947c90aa4908f88d24035fc5a79b05719fc9a71c1845581c6f95b454a73bb2258d447c2ac26528f2a8de7d3f02eb734b137de625b55e9f9b
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 12
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      LUNA_TOKEN: 71f9b3e0-51b1-480f-93b9-0e76e260bcbc
      LUNA_ADDRESS: 'http://172.17.0.1'
#      LUNA_ADDRESS: ${LUNA_ADDRESS}
      LUNA_PORT: '5000'
      LUNA_API_VERSION: 4
      ACS_SFTP_HOST: 172.26.27.80
      ACS_SFTP_USERNAME: sftpuser
      ACS_SFTP_PASSWORD: P@ssw0rd
    volumes:
      - app_files:/opt/app/public/system
      - /opt/app/public
    ports:
      - "9292"
    restart: always

  jobs:
    image: video-bi/app:latest
    environment:
      <<: *ENVIRONMENT
    volumes_from:
      - app:ro
    command: bundle exec sidekiq -q default -q mailers -q recognition -q slack
    restart: always
  
  job_telegram:
    image: video-bi/app:latest
    environment:
      <<: *ENVIRONMENT
    #http_proxy: http://ip:port
    #https_proxy: https://ip:port
    volumes_from:
      - app:ro
    command: bundle exec sidekiq -q telegram
    restart: always

  redis:
    image: redis:3.0.5
    ports:
      - "6379"
    volumes:
      - data_redis:/data
    restart: always
    
  web:
    image: nginx:stable
    volumes_from:
      - app:ro
    volumes:
      - /var/lib/luna/video-bi/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/lib/luna/video-bi/nginx/vbi.conf:/etc/nginx/vbi.conf:ro
      - /var/lib/luna/video-bi/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "5280:80"
      - "5205:5205"
    restart: always

volumes:
  pg_data:
    external: false
  data_redis:
    external: false
  app_files:
    external: false
